In [20]:
import os
os.getcwd()

'C:\\Users\\Vansh'

In [21]:
import numpy as np
import pandas as pd
import sklearn 
sklearn.__version__

'1.7.2'

In [22]:
dataset = pd.read_csv('diabetes.csv')
print(dataset.head())
dataset.info()
cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Age', 'BMI']
for col in cols:
    dataset[col] = dataset[col].replace(0, dataset[col].median())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768

In [23]:
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,23,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,23,0,30.1,0.349,47


In [24]:
from sklearn.model_selection  import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)
y_train

60     0
618    1
346    0
294    0
231    1
      ..
71     0
106    0
270    1
435    1
102    0
Name: Outcome, Length: 614, dtype: int64

In [25]:
from sklearn.preprocessing import StandardScaler
scaled =  StandardScaler()
X_train = scaled.fit_transform(X_train)
X_test = scaled.transform(X_test)
X_train , X_test

(array([[-0.52639686, -1.25688146, -0.01899526, ..., -0.05024677,
         -0.49073479, -1.03594038],
        [ 1.58804586, -0.32605067,  0.8081742 , ..., -0.59858988,
          2.41502991,  1.48710085],
        [-0.82846011,  0.57153617, -2.16963585, ..., -0.52643947,
          0.54916055, -0.94893896],
        ...,
        [ 1.8901091 , -0.69173419,  1.13904198, ...,  1.91224437,
          1.981245  ,  0.44308379],
        [-1.13052335,  0.63802409, -0.01899526, ...,  1.45048175,
         -0.78487662, -0.33992901],
        [-1.13052335,  0.10612077,  1.96621144, ..., -1.42110454,
         -0.61552223, -1.03594038]], shape=(614, 8)),
 array([[ 0.68185612, -0.79146606, -1.1770325 , ...,  0.23835487,
         -0.11637247,  0.87809089],
        [-0.52639686, -0.32605067,  0.22915558, ...,  0.48366626,
         -0.954231  , -1.03594038],
        [-0.52639686, -0.45902649, -0.68073083, ..., -0.22340775,
         -0.9245197 , -1.03594038],
        ...,
        [ 1.28598261, -0.89119794, -0.

In [26]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(X_train , y_train)
y_pred = (lg.predict(X_test))
y_pred,y_test

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 668    0
 324    0
 624    0
 690    0
 473    0
       ..
 355    1
 534    0
 344    0
 296    1
 462    0
 Name: Outcome, Length: 154, dtype: int64)

In [27]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test , y_pred)
print(f"Model Accuracy : {score*100:.2f}%")

Model Accuracy : 76.62%


In [30]:
pregnancies = int(input("Enter Pregnancies: "))
glucose = int(input("Enter Glucose: "))
bp = int(input("Enter Blood Pressure: "))
skin = int(input("Enter Skin Thickness: "))
insulin = int(input("Enter Insulin: "))
bmi = float(input("Enter BMI: "))
dpf = float(input("Enter Diabetes Pedigree Function: "))
age = int(input("Enter Age: "))

user_data = pd.DataFrame([[pregnancies, glucose, bp, skin, insulin, bmi, dpf, age]] , columns = list(X.columns) , index = none)
print(user_data)
user_data = scaled.transform(user_data)


prediction = lg.predict(user_data)

if prediction[0] == 1:
    print("Diabetes Detected")
else:
    print("No Diabetes")

Enter Pregnancies:  0
Enter Glucose:  222
Enter Blood Pressure:  25
Enter Skin Thickness:  23
Enter Insulin:  120
Enter BMI:  32
Enter Diabetes Pedigree Function:  0.6
Enter Age:  55


TypeError: Index(...) must be called with a collection of some kind, False was passed